/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.BorderLayout;
import java.awt.Color;
import notification.Notification;

/**
 *
 * @author Ayair Martin
 */
public class MenuPrinci extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrinci
     */
    public MenuPrinci() {
        initComponents();
        this.setLocationRelativeTo(null);
        //this.setBackground(new Color(0,0,0,0));
        
        Home h = new Home();
        h.setSize(2000,900);
        h.setLocation(0,0);
        
        contenedor.removeAll();
        contenedor.add(h,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnhome = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnclientes = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnentradas = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnsalidas = new RSMaterialComponent.RSButtonMaterialIconDos();
        jSeparator1 = new javax.swing.JSeparator();
        btnacercade = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnsalir = new RSMaterialComponent.RSButtonMaterialIconDos();
        btncategorias = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnusuarios = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnproveedor = new RSMaterialComponent.RSButtonMaterialIconDos();
        contenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(50, 28, 145));

        jLabel1.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INVENTARIO");

        btnhome.setBackground(new java.awt.Color(50, 28, 145));
        btnhome.setText("HOME");
        btnhome.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HOME);
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });

        btnclientes.setBackground(new java.awt.Color(50, 28, 145));
        btnclientes.setText("CLIENTES");
        btnclientes.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PEOPLE);
        btnclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclientesActionPerformed(evt);
            }
        });

        btnentradas.setBackground(new java.awt.Color(50, 28, 145));
        btnentradas.setText("ENTRADAS");
        btnentradas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnentradas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.INPUT);
        btnentradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentradasActionPerformed(evt);
            }
        });

        btnsalidas.setBackground(new java.awt.Color(50, 28, 145));
        btnsalidas.setText("SALIDAS");
        btnsalidas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.OPEN_IN_NEW);
        btnsalidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalidasActionPerformed(evt);
            }
        });

        btnacercade.setBackground(new java.awt.Color(50, 28, 145));
        btnacercade.setText("ACERCA DE");
        btnacercade.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HELP);
        btnacercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnacercadeActionPerformed(evt);
            }
        });

        btnsalir.setBackground(new java.awt.Color(255, 0, 51));
        btnsalir.setText("SALIR");
        btnsalir.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EXIT_TO_APP);
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        btncategorias.setBackground(new java.awt.Color(50, 28, 145));
        btncategorias.setText("CATEGORIAS");
        btncategorias.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DASHBOARD);
        btncategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncategoriasActionPerformed(evt);
            }
        });

        btnusuarios.setBackground(new java.awt.Color(50, 28, 145));
        btnusuarios.setText("USUARIOS");
        btnusuarios.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.GROUP_ADD);
        btnusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnusuariosActionPerformed(evt);
            }
        });

        btnproveedor.setBackground(new java.awt.Color(50, 28, 145));
        btnproveedor.setText("PROVEEDOR");
        btnproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(67, 67, 67))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsalidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnentradas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnusuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnproveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(btnsalir, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(btnacercade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnhome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(btnclientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncategorias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnhome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnclientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnentradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsalidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnacercade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        contenedor.setBackground(new java.awt.Color(255, 255, 255));
        contenedor.setPreferredSize(new java.awt.Dimension(940, 0));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncategoriasActionPerformed
        // boton categoria de menu principal
        
        btncategorias.setSelected(true);
        btnhome.setSelected(false);
        btnclientes.setSelected(false);
        btnproveedor.setSelected(false);
        btnentradas.setSelected(false);
        btnsalidas.setSelected(false);
        btnusuarios.setSelected(false);
        btnacercade.setSelected(false);
        
        
        Categorias c = new Categorias();
        c.setSize(982,800);
        c.setLocation(0,0);
        
        contenedor.removeAll();
        contenedor.add(c,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
        
        
        
    }//GEN-LAST:event_btncategoriasActionPerformed

    private void btnclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclientesActionPerformed
        // boton clientes
        btncategorias.setSelected(false);
        btnclientes.setSelected(true);
        btnhome.setSelected(false);
        btnentradas.setSelected(false);
        btnproveedor.setSelected(false);
        btnsalidas.setSelected(false);
        btnusuarios.setSelected(false);
        btnacercade.setSelected(false);
        
        Clientes c = new Clientes();
        c.setSize(982,940);
        c.setLocation(0,0);
        
        contenedor.removeAll();
        contenedor.add(c,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
        
        
        
    }//GEN-LAST:event_btnclientesActionPerformed

    private void btnentradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentradasActionPerformed
        // TODO add your handling code here:
        // boton entradas
        btncategorias.setSelected(false);
        btnclientes.setSelected(false);
        btnhome.setSelected(false);
        btnentradas.setSelected(true);
        btnproveedor.setSelected(false);
        btnsalidas.setSelected(false);
        btnusuarios.setSelected(false);
        btnacercade.setSelected(false);
        
        Entradas c = new Entradas();
        c.setSize(1000,1200);
        c.setLocation(0,0);
        
        contenedor.removeAll();
        contenedor.add(c,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
        
    }//GEN-LAST:event_btnentradasActionPerformed

    private void btnsalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalidasActionPerformed
        // TODO add your handling code here:
        // boton salidas
        btncategorias.setSelected(false);
        btnclientes.setSelected(false);
        btnhome.setSelected(false);
        btnentradas.setSelected(false);
        btnproveedor.setSelected(false);
        btnsalidas.setSelected(true);
        btnusuarios.setSelected(false);
        btnacercade.setSelected(false);
        
        Salidas c = new Salidas();
        c.setSize(1000,800);
        c.setLocation(0,0);
        
        contenedor.removeAll();
        contenedor.add(c,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
        
        
    }//GEN-LAST:event_btnsalidasActionPerformed

    private void btnusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnusuariosActionPerformed
        // TODO add your handling code here:
        // boton usuario
        btncategorias.setSelected(false);
        btnclientes.setSelected(false);
        btnhome.setSelected(false);
        btnentradas.setSelected(false);
        btnproveedor.setSelected(false);
        btnsalidas.setSelected(false);
        btnusuarios.setSelected(true);
        btnacercade.setSelected(false);
        
        Usuarios c = new Usuarios();
        c.setSize(1120, 600);
        c.setLocation(0,0);
        
        contenedor.removeAll();
        contenedor.add(c,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
        
    }//GEN-LAST:event_btnusuariosActionPerformed

    private void btnacercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnacercadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnacercadeActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        login m = new login();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproveedorActionPerformed
        // TODO add your handling code here:
        // boton clientes
        btncategorias.setSelected(false);
        btnclientes.setSelected(false);
        btnhome.setSelected(false);
        btnentradas.setSelected(false);
        btnproveedor.setSelected(true);
        btnsalidas.setSelected(false);
        btnusuarios.setSelected(false);
        btnacercade.setSelected(false);
        
        Proveedor c = new Proveedor();
        c.setSize(1000,1200);
        c.setLocation(0,0);
        
        contenedor.removeAll();
        contenedor.add(c,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
        
    }//GEN-LAST:event_btnproveedorActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        // BOTON HOME
        
        btnhome.setSelected(true);
        btncategorias.setSelected(false);
        btnclientes.setSelected(false);
        btnsalidas.setSelected(false);
        btnusuarios.setSelected(false);
        btnacercade.setSelected(false);
        Home h = new Home();
        h.setSize(1000,900);
        h.setLocation(0,0);
        
        contenedor.removeAll();
        contenedor.add(h,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
        
    }//GEN-LAST:event_btnhomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrinci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrinci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrinci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrinci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrinci().setVisible(true);
            }
        });
    }
    
    public void exito(String texto){
        Notification panel = new Notification(this, Notification.Type.SUCCESS, Notification.Location.TOP_RIGHT, texto);
        panel.showNotification();
    }
    
    public void warning(String texto){
        Notification panel = new Notification(this, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, texto);
        panel.showNotification();
    }
    
    public void error(String texto){
        Notification panel = new Notification(this, Notification.Type.ERROR, Notification.Location.TOP_RIGHT, texto);
        panel.showNotification();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconDos btnacercade;
    private RSMaterialComponent.RSButtonMaterialIconDos btncategorias;
    private RSMaterialComponent.RSButtonMaterialIconDos btnclientes;
    private RSMaterialComponent.RSButtonMaterialIconDos btnentradas;
    private RSMaterialComponent.RSButtonMaterialIconDos btnhome;
    private RSMaterialComponent.RSButtonMaterialIconDos btnproveedor;
    private RSMaterialComponent.RSButtonMaterialIconDos btnsalidas;
    private RSMaterialComponent.RSButtonMaterialIconDos btnsalir;
    private RSMaterialComponent.RSButtonMaterialIconDos btnusuarios;
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
